In [ ]:
CSCI 164 Project - Section 1 Dataset exploration
Datasets:
1. Gaming_Academic_Performance.csv
2. AI_Impact_Student_Life_2026.csv
Project Idea: The project explores 2 areas that I continue to be interested in, ai and gaming.
Not on how the two interact, but how gaming and ai is something I use as a student. I enjoy gaming
to an extent on my free time and I use ai extensively for school, but for outside usuage when new
updates come to ai such as chatgpt or claude. These datasets were perfect for those aspects and how
it impacts fellow students.

In [ ]:
Dataset 1: Gaming_Academic_Performance.csv
The dataset was selected because it was clean, no missing values, contains a strong target
variable, and has multiple features related to students. 
Also, it is good for regression modeling and is easy to interpret.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset 1
df1 = pd.read_csv("Gaming_Academic_Performance.csv")

print("Shape:", df1.shape)
print("\nColumns:")
print(df1.columns.tolist())

print("\nData types:")
print(df1.dtypes)

print("\nMissing values:")
print(df1.isnull().sum())

display(df1.head())

Shape: (8000, 14)

Columns:
['student_id', 'age', 'gender', 'gaming_hours', 'study_hours', 'sleep_hours', 'attendance', 'gaming_genre', 'social_activity', 'device_usage', 'reaction_time_ms', 'addiction_score', 'stress_level', 'grades']

Data types:
student_id            int64
age                   int64
gender               object
gaming_hours        float64
study_hours         float64
sleep_hours         float64
attendance          float64
gaming_genre         object
social_activity     float64
device_usage        float64
reaction_time_ms    float64
addiction_score     float64
stress_level         object
grades              float64
dtype: object

Missing values:
student_id          0
age                 0
gender              0
gaming_hours        0
study_hours         0
sleep_hours         0
attendance          0
gaming_genre        0
social_activity     0
device_usage        0
reaction_time_ms    0
addiction_score     0
stress_level        0
grades              0
dtype: int64

,student_id,age,gender,gaming_hours,study_hours,sleep_hours,attendance,gaming_genre,social_activity,device_usage,reaction_time_ms,addiction_score,stress_level,grades
0,1,22,Male,7.23,8.78,6.96,91.44,FPS,3.25,9.36,235.84,14.69,Low,86.459555
1,2,19,Male,0.07,8.72,7.63,63.63,Casual,1.02,3.21,328.71,2.47,Medium,98.230000
2,3,23,Female,1.73,9.56,4.40,83.26,Casual,3.46,5.56,313.61,4.73,High,90.560000
3,4,20,Female,6.62,1.68,7.83,75.04,RPG,1.46,11.78,241.84,14.54,Low,32.670000
4,5,22,Female,5.36,5.83,5.55,65.57,FPS,1.01,8.23,249.31,12.48,Low,58.710000

In [ ]:
Dataset Structure:
- **Rows:** 8000
- **Columns:** 14
- **Target Variable:** `grades`
- **Task Type:** Regression

Features:
- `gaming_hours`
- `study_hours`
- `sleep_hours`
- `attendance`
- `social_activity`
- `device_usage`
- `reaction_time_ms`
- `addiction_score`
- `stress_level`
- `gender`
- `gaming_genre`

In [3]:
#Drop Id
df1 = df1.drop(columns=["student_id"])

#Features
X1 = df1.drop(columns=["grades"])
y1 = df1["grades"]

#Types
numeric_features_1 = X1.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features_1 = X1.select_dtypes(include=["object"]).columns.tolist()

print("Numeric features:", numeric_features_1)
print("Categorical features:", categorical_features_1)

Numeric features: ['age', 'gaming_hours', 'study_hours', 'sleep_hours', 'attendance', 'social_activity', 'device_usage', 'reaction_time_ms', 'addiction_score']
Categorical features: ['gender', 'gaming_genre', 'stress_level']

In [ ]:
#Processing Plan
Steps:
1. Remove indentifier column (student id)
2. Missing values (no missing values present)
3. Encode catergorical variables (gender/gaming genre converted with hot-one)
4. Normalize numerical variables

In [ ]:
Dataset 1: AI_Impact_Student_Life_2026.csv
The dataset was selected because it focus on the same idea with students, but about ai usage. 
It contains both numerical and categorical features, no missing values again, and strong
targets and GPA change with ai usage.

In [4]:
# Dataset 2
df2 = pd.read_csv("AI_Impact_Student_Life_2026.csv")

print("Shape:", df2.shape)
print("\nColumns:")
print(df2.columns.tolist())

print("\nData types:")
print(df2.dtypes)

print("\nMissing values:")
print(df2.isnull().sum())

display(df2.head())

Shape: (1500, 11)

Columns:
['Student_ID', 'Age', 'Major', 'Primary_AI_Tool', 'Task_Frequency_Daily', 'Main_Usage_Case', 'GPA_Baseline', 'GPA_Post_AI', 'Time_Saved_Hours_Weekly', 'AI_Ethics_Concern', 'Career_Confidence_Score']

Data types:
Student_ID                  object
Age                          int64
Major                       object
Primary_AI_Tool             object
Task_Frequency_Daily         int64
Main_Usage_Case             object
GPA_Baseline               float64
GPA_Post_AI                float64
Time_Saved_Hours_Weekly      int64
AI_Ethics_Concern           object
Career_Confidence_Score      int64
dtype: object

Missing values:
Student_ID                 0
Age                        0
Major                      0
Primary_AI_Tool            0
Task_Frequency_Daily       0
Main_Usage_Case            0
GPA_Baseline               0
GPA_Post_AI                0
Time_Saved_Hours_Weekly    0
AI_Ethics_Concern          0
Career_Confidence_Score    0
dtype: int64

,Student_ID,Age,Major,Primary_AI_Tool,Task_Frequency_Daily,Main_Usage_Case,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,AI_Ethics_Concern,Career_Confidence_Score
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7
3,STU-1380,19,Biology,Claude 3.5,5,Essay Drafting,2.67,2.87,12,Low,5
4,STU-1837,19,Biology,ChatGPT-4o,10,Code Debugging,3.65,3.85,5,High,9

In [5]:
# Create GPA change feature
df2["GPA_Change"] = df2["GPA_Post_AI"] - df2["GPA_Baseline"]

display(df2[["GPA_Baseline", "GPA_Post_AI", "GPA_Change"]].head())

   GPA_Baseline  GPA_Post_AI  GPA_Change
0          2.62         2.62        0.00
1          3.99         4.00        0.01
2          2.57         2.57        0.00
3          2.67         2.87        0.20
4          3.65         3.85        0.20

In [ ]:
## Dataset 2 Structure
- **Rows:** 1500
- **Columns:** 11 original columns (plus 1 derived feature: `GPA_Change`)
- **Target Variable:** `GPA_Change` (preferred) or `GPA_Post_AI`
- **Task Type:** Regression

###Features:
- `Age`
- `Major`
- `Primary_AI_Tool`
- `Task_Frequency_Daily`
- `Main_Usage_Case`
- `GPA_Baseline`
- `Time_Saved_Hours_Weekly`
- `AI_Ethics_Concern`
- `Career_Confidence_Score`

In [6]:
# DropID
df2 = df2.drop(columns=["Student_ID"])

#GPA_Change as target
X2 = df2.drop(columns=["GPA_Change"])
y2 = df2["GPA_Change"]

#Types
numeric_features_2 = X2.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features_2 = X2.select_dtypes(include=["object"]).columns.tolist()

print("Numeric features:", numeric_features_2)
print("Categorical features:", categorical_features_2)

Numeric features: ['Age', 'Task_Frequency_Daily', 'GPA_Baseline', 'GPA_Post_AI', 'Time_Saved_Hours_Weekly', 'Career_Confidence_Score']
Categorical features: ['Major', 'Primary_AI_Tool', 'Main_Usage_Case', 'AI_Ethics_Concern']

In [ ]:
Processing Plan
Steps:
1. Remove indentifier column (student id)
2. Feature working (GPA_change - base and ai usage)
3. Missing values (no missing values)
4. Encode Categorical values (major, primary ai tool, main usage case)
5. Normalize numerical variables

In [ ]:
Dataset 1 Prior work:
Mahmud et al. (2023), Online gaming and its effect on academic performance, sleep, and physical activity in university students.
https://pmc.ncbi.nlm.nih.gov/articles/PMC10723781/
This study is relevant to the project because the dataset used is very similar to the one I am using with similar variables.
The study reported that students who played games for long periods, especially 30+ hours per week, tended to have lower GPA, 
less physical activity, and less study time. This supports the use of the `Gaming_Academic_Performance.csv` dataset 
for predicting grades from gaming and lifestyle factors.

In [ ]:
Dataset 2 Prior work:
prior study is **Wecks et al. (2024), Generative AI Usage and Exam Performance. In this study, they investigated how students use of generative AI tools such as ChatGPT related to exam performance. 
They identified that AI users through analysis of student essays and then applied multivariate regression analysis to compare performance outcomes. 
The study reported that students who used generative AI tools scored, on average, 6.71 points lower (out of 100) than non-users.
Relevant to project since the dataset I am using has similar variables, similar outcomes, and ai usage.
https://arxiv.org/abs/2404.19699